AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*' 

  NewCops: enable

  TargetRubyVersion: 3.4
  
  AutoCorrect: true

Style:
  StringLiterals:
    EnforcedStyle: double_quotes

  ParameterLists:
    EnforcedStyle: compact

  RedundantSelf:
    Enabled: true

  ModifierForm:
    AllowModifierForm: true

Layout:
  LineLength:
    Max: 120

  FirstParameterIndentation:
   恩abled: true
    EnforcedStyle: indented

Indentation:
  Width:
    Width: 2

Metrics:
  ClassLength:
    Max: 200

  MethodLength:
    Max: 20

  ParameterLists:
    Max: 5

Lint/AmbiguousOperator:
  Enabled: false

Style/Documentation:
  Enabled: false 

Style/AccessModifierDeclarations:
  Enabled: false 
